version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      releaseway:
        patterns:
          - releaseway/actions
          - releaseway/homebrew-actions/.github/workflows/check.yml
          - releaseway/homebrew-actions/.github/workflows/publish.yml
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - releaseway/actions
          - releaseway/homebrew-actions/.github/workflows/check.yml
          - releaseway/homebrew-actions/.github/workflows/publish.yml
