name: auto-merge homebrew-tap updates

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  auto-merge:
    uses: jinyongp/homebrew-tap/.github/workflows/auto-merge-homebrew-tap.yml@5d4694353a9ed933fe0be9055ca64b7eef53e4f0 # automation-v1.5.0
