name: homebrew

on:
  pull_request:

permissions:
  contents: read

jobs:
  homebrew:
    uses: jinyongp/homebrew-tap/.github/workflows/publish-formula.yml@5d4694353a9ed933fe0be9055ca64b7eef53e4f0 # automation-v1.5.0
    with:
      formula: openapi-sdkgen
      dry-run: true
      validation-mode: spec
